# Generated by Django 6.0.4 on 2026-04-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='media_type',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='image_videos/'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_posts/'),
        ),
    ]
