# Generated by Django 4.2.27 on 2026-01-26 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='estbalis_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addpropertymodel',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='addpropertymodel',
            name='furniture',
            field=models.CharField(blank=True, choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='addpropertymodel',
            name='nearByPlaces',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
