# Generated by Django 6.0.4 on 2026-04-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0002_remove_newspost_media_type_imagepost_heading_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='video',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='news_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='NewsPost',
        ),
    ]
