# Generated by Django 4.2.27 on 2026-02-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0002_addproject_estbalis_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpropertymodel',
            name='deposit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
