# Generated by Django 4.2.27 on 2026-02-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0003_addpropertymodel_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_amount',
            field=models.IntegerField(default=0),
        ),
    ]
