# Generated by Django 6.0.4 on 2026-04-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0003_remove_imagepost_description_remove_imagepost_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_posts/'),
        ),
    ]
