# Generated by Django 4.2.27 on 2026-02-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0004_user_subscription_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_amount',
        ),
        migrations.AlterField(
            model_name='user',
            name='referred_by_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_referral_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
