# Generated by Django 6.0.4 on 2026-04-23 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0004_imagepost_media_type_imagepost_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text Only')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='news_videos/')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('news_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
