# Generated by Django 4.2.27 on 2026-02-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0005_remove_user_radius_remove_user_subscription_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_google_user',
            field=models.BooleanField(default=False),
        ),
    ]
