# Generated by Django 6.0.4 on 2026-04-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0005_newspost'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='linked_property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prop.addpropertymodel'),
        ),
        migrations.CreateModel(
            name='ProjectLegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='project_legal_docs/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_documents', to='prop.addproject')),
            ],
        ),
    ]
