# Generated by Django 4.2.27 on 2026-02-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0006_user_is_google_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='radius',
            field=models.IntegerField(default=5),
        ),
    ]
