# Generated by Django 4.2.27 on 2026-02-20 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0007_user_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('PROFESSIONAL', 'Professional'), ('MARKETER_EXPERT', 'Marketer Expert'), ('MARKETER_EXPERT_PRO', 'Marketer Expert Pro'), ('COMPANY_SILVER', 'Company Silver'), ('COMPANY_PLATINUM', 'Company Platinum'), ('COMPANY_GOLD', 'Company Gold')], max_length=50)),
                ('amount', models.IntegerField()),
                ('razorpay_order_id', models.CharField(max_length=200)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=300, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
