# Generated by Django 4.2.27 on 2026-02-23 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0008_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='plan_type',
        ),
        migrations.AlterField(
            model_name='addproject',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('MARKETER_EXPORT', 'Marketer Export'), ('MARKETER_EXPORT_PRO', 'Marketer Export Pro'), ('MARKETER_EXPORT_PREMIUM', 'Marketer Export Premium'), ('PROFESSIONAL_SINGLE', 'Professional Single'), ('COMPANY_NORMAL', 'Company Normal'), ('COMPANY_PRO', 'Company Pro'), ('COMPANY_PREMIUM', 'Company Premium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_subscription_type',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('PRO', 'Pro'), ('PREMIUM', 'Premium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='marketing_subscription_type',
            field=models.CharField(blank=True, choices=[('EXPORT', 'Export'), ('EXPORT_PRO', 'Export Pro'), ('EXPORT_PREMIUM', 'Export Premium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('MARKETER_EXPORT', 'Marketer Export'), ('MARKETER_EXPORT_PRO', 'Marketer Export Pro'), ('MARKETER_EXPORT_PREMIUM', 'Marketer Export Premium'), ('PROFESSIONAL_SINGLE', 'Professional Single'), ('COMPANY_NORMAL', 'Company Normal'), ('COMPANY_PRO', 'Company Pro'), ('COMPANY_PREMIUM', 'Company Premium')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='professionals_subscription_type',
            field=models.CharField(blank=True, choices=[('EXPORT', 'Export'), ('EXPORT_PRO', 'Export Pro'), ('EXPORT_PREMIUM', 'Export Premium')], max_length=50, null=True),
        ),
    ]
