# Generated by Django 4.2.27 on 2026-02-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0009_remove_payment_is_paid_remove_payment_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner_subscription_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='owner_subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addproject',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('MARKETER_EXPORT', 'Marketer Export'), ('MARKETER_EXPORT_PRO', 'Marketer Export Pro'), ('MARKETER_EXPORT_PREMIUM', 'Marketer Export Premium'), ('PROFESSIONAL_SINGLE', 'Professional Single'), ('COMPANY_NORMAL', 'Company Normal'), ('COMPANY_PRO', 'Company Pro'), ('COMPANY_PREMIUM', 'Company Premium'), ('OWNER', 'Owner')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('MARKETER_EXPORT', 'Marketer Export'), ('MARKETER_EXPORT_PRO', 'Marketer Export Pro'), ('MARKETER_EXPORT_PREMIUM', 'Marketer Export Premium'), ('PROFESSIONAL_SINGLE', 'Professional Single'), ('COMPANY_NORMAL', 'Company Normal'), ('COMPANY_PRO', 'Company Pro'), ('COMPANY_PREMIUM', 'Company Premium'), ('OWNER', 'Owner')], max_length=30, null=True),
        ),
    ]
