# Generated by Django 4.2.27 on 2026-02-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0010_user_owner_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
