# Generated by Django 4.2.27 on 2026-02-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0011_slideimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addproject',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addpropertymodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='addpropertymodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
