# Generated by Django 4.2.27 on 2026-03-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0012_addproject_latitude_addproject_longitude_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpropertymodel',
            old_name='location',
            new_name='address',
        ),
    ]
