# Generated by Django 4.2.27 on 2026-03-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0013_rename_location_addpropertymodel_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addproject',
            old_name='project_location',
            new_name='project_address',
        ),
    ]
