# Generated by Django 4.2.27 on 2026-03-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0014_rename_project_location_addproject_project_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
