# Generated by Django 4.2.27 on 2026-03-06 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0015_reels_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_bg/')),
                ('video', models.FileField(blank=True, null=True, upload_to='category_bg/')),
            ],
        ),
        migrations.AddField(
            model_name='slideimage',
            name='slide_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
