# Generated by Django 4.2.27 on 2026-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0016_categorymedia_slideimage_slide_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideimage',
            name='slide_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], default='desktop', max_length=10),
        ),
    ]
