# Generated by Django 4.2.27 on 2026-03-10 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0018_alter_slideimage_slide_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryMedia',
        ),
    ]
