# Generated by Django 4.2.27 on 2026-03-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0020_savedproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='addproject',
            name='nearby_location_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addproject',
            name='nearby_location_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addproject',
            name='nearby_location_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='addproject',
            name='nearby_location_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
