# Generated by Django 4.2.27 on 2026-04-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0022_remove_chatroom_is_online_remove_chatroom_last_seen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addproject',
            name='nearby_location_1',
        ),
        migrations.RemoveField(
            model_name='addproject',
            name='nearby_location_2',
        ),
        migrations.RemoveField(
            model_name='addproject',
            name='nearby_location_3',
        ),
        migrations.RemoveField(
            model_name='addproject',
            name='nearby_location_4',
        ),
        migrations.AddField(
            model_name='addproject',
            name='nearby_locations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
