# Generated by Django 4.2.27 on 2026-04-07 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0023_remove_addproject_nearby_location_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewed_reels', to=settings.AUTH_USER_MODEL),
        ),
    ]
