# Generated by Django 4.2.27 on 2026-04-08 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0024_reels_viewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addpropertymodel',
            name='nearByPlaces',
        ),
    ]
