# Generated by Django 4.2.27 on 2026-04-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prop', '0025_remove_addpropertymodel_nearbyplaces'),
    ]

    operations = [
        migrations.AddField(
            model_name='addpropertymodel',
            name='nearby_places',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
